SHELL := /bin/bash
.DEFAULT_GOAL := help

# Local development against the Supabase CLI stack (Postgres + Auth + Storage + Mailpit).
# Requires Docker + the Supabase CLI. The backend's app tables are created by
# SQLAlchemy create_all() on first connect; the local DB schema therefore matches prod.

.PHONY: help up down reset status dev-backend dev-frontend seed test test-integration e2e latex-up latex-down latex-tunnel

# Local dev uses the repo venv; CI overrides with PY=python.
PY ?= .venv/bin/python

# Ports are parameterizable so several worktrees (e.g. parallel agents) can each run
# their own backend+frontend against the one shared Supabase stack. Pick a distinct
# pair per worktree and pass BOTH to BOTH targets:
#   make dev-backend  BACKEND_PORT=8001 FRONTEND_PORT=3001
#   make dev-frontend BACKEND_PORT=8001 FRONTEND_PORT=3001
BACKEND_PORT ?= 8000
FRONTEND_PORT ?= 3000

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

up: ## Start the local Supabase stack
	set -a; [ -f supabase/.env.local ] && . supabase/.env.local; set +a; supabase start

down: ## Stop the local Supabase stack
	supabase stop

reset: ## Wipe + recreate the local database (re-runs create_all on next backend start)
	supabase db reset

status: ## Show local stack URLs/keys
	supabase status

# Pull local creds from `supabase status` and map them onto the backend's env names,
# then run uvicorn. python-dotenv (load_dotenv) does NOT override real env vars, so these
# exported local values win over the committed cloud .env.
dev-backend: ## Run the FastAPI backend against the local stack
	set -a; \
	eval "$$(supabase status -o env 2>/dev/null | grep -E '^[A-Z0-9_]+=')"; \
	if [ -z "$$DB_URL" ]; then \
	  echo "ERROR: couldn't read local Supabase creds (DATABASE_URL would be empty)."; \
	  echo "  - Run 'make up' first if the stack isn't running."; \
	  echo "  - Docker must be reachable from this shell ('docker ps' must work). On snap-Docker/WSL"; \
	  echo "    the 'docker' group needs a fresh login: run 'newgrp docker' (or restart WSL), or use:"; \
	  echo "    sg docker -c 'make dev-backend'"; \
	  exit 1; \
	fi; \
	export SUPABASE_URL="$$API_URL" \
	       SUPABASE_PUBLISHABLE_KEY="$$PUBLISHABLE_KEY" \
	       SUPABASE_SECRET_KEY="$$SECRET_KEY" \
	       SUPABASE_JWT_SECRET="$$JWT_SECRET" \
	       DATABASE_URL="$$DB_URL" \
	       LATEX_COMPILER_BASE_URL="http://127.0.0.1:2700" \
	       CORS_ALLOWED_ORIGINS="http://localhost:$(FRONTEND_PORT),http://127.0.0.1:$(FRONTEND_PORT)" \
	       ENVIRONMENT="development"; \
	set +a; \
	.venv/bin/uvicorn backend.main:app --reload --host 127.0.0.1 --port $(BACKEND_PORT)

dev-frontend: ## Run the Next.js frontend against the local stack (auto-creates frontend/.env.local)
	# On first run, create frontend/.env.local from the local stack so a fresh clone needs
	# no manual frontend config. The local keys are the Supabase CLI's deterministic demo
	# values (not secrets). Won't overwrite an existing file (delete it to change ports).
	@if [ ! -f frontend/.env.local ]; then \
	  eval "$$(supabase status -o env 2>/dev/null | grep -E '^[A-Z0-9_]+=')"; \
	  if [ -z "$$PUBLISHABLE_KEY" ]; then \
	    echo "ERROR: couldn't read local Supabase creds to create frontend/.env.local."; \
	    echo "  Run 'make up' first, and ensure Docker is reachable ('docker ps' works) —"; \
	    echo "  on snap-Docker/WSL: 'newgrp docker' or 'sg docker -c \"make dev-frontend\"'."; \
	    exit 1; \
	  fi; \
	  printf '%s\n' \
	    "# Auto-generated by 'make dev-frontend' from the local Supabase stack. Delete to regenerate." \
	    "# Browser reaches Supabase via the Next same-origin proxy; server uses the direct URL." \
	    "NEXT_PUBLIC_SUPABASE_URL=http://localhost:$(FRONTEND_PORT)" \
	    "SUPABASE_LOCAL_PROXY_TARGET=$$API_URL" \
	    "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$$PUBLISHABLE_KEY" \
	    "NEXT_PUBLIC_API_URL=http://localhost:$(BACKEND_PORT)" \
	    "API_URL=http://localhost:$(BACKEND_PORT)" \
	    > frontend/.env.local; \
	  echo "created frontend/.env.local (frontend :$(FRONTEND_PORT), backend :$(BACKEND_PORT))"; \
	elif ! grep -q "NEXT_PUBLIC_SUPABASE_URL=http://localhost:$(FRONTEND_PORT)$$" frontend/.env.local; then \
	  echo "WARNING: frontend/.env.local was generated for other ports — delete it to regenerate."; \
	fi
	# Clear the (possibly stale on WSL) Turbopack cache so dev styling matches prod.
	rm -rf frontend/.next
	cd frontend && PORT=$(FRONTEND_PORT) npm run dev

seed: ## Create a confirmed local test user ([email protected] / password123)
	@eval "$$(supabase status -o env 2>/dev/null | grep -E '^[A-Z0-9_]+=')"; \
	curl -s -X POST "$$API_URL/auth/v1/admin/users" \
	  -H "apikey: $$SERVICE_ROLE_KEY" -H "Authorization: Bearer $$SERVICE_ROLE_KEY" \
	  -H "Content-Type: application/json" \
	  -d '{"email":"[email protected]","password":"password123","email_confirm":true}' >/dev/null \
	  && echo "seeded: [email protected] / password123" || echo "seed failed"

test: ## Run the unit test lane (no DB, network, or secrets needed)
	$(PY) -m pytest -q

test-integration: ## Run unit+integration lanes against the local Supabase stack (make up first)
	@set -a; \
	eval "$$(supabase status -o env 2>/dev/null | grep -E '^[A-Z0-9_]+=')"; \
	if [ -z "$$DB_URL" ]; then echo "ERROR: local stack not running ('make up' first)"; exit 1; fi; \
	export SUPABASE_URL="$$API_URL" \
	       SUPABASE_PUBLISHABLE_KEY="$$PUBLISHABLE_KEY" \
	       SUPABASE_SECRET_KEY="$$SECRET_KEY" \
	       SUPABASE_SERVICE_ROLE_KEY="$$SERVICE_ROLE_KEY" \
	       SUPABASE_JWT_SECRET="$$JWT_SECRET" \
	       DATABASE_URL="$$DB_URL" \
	       ENVIRONMENT="development"; \
	set +a; \
	$(PY) -m pytest -q -m "not real_ai" $(PYTEST_ARGS)

e2e: ## Full-stack Playwright smoke (needs 'make up' + 'make latex-up' first)
	./scripts/e2e-stack.sh

# Local LaTeX compiler (PDF generation). Same image as prod and CI: TeX Live
# 2024 + latex-online baked in, served on 127.0.0.1:2700. Pulled from GHCR
# when available (fast); falls back to a local build (~4-5GB base pull).
# The backend defaults LATEX_COMPILER_BASE_URL to this address.
latex-up: ## Pull (or build) + start the local LaTeX compiler on 127.0.0.1:2700
	docker image inspect ghcr.io/zumud/zumud-latex:latest >/dev/null 2>&1 \
	  || docker pull ghcr.io/zumud/zumud-latex:latest \
	  || docker build -t ghcr.io/zumud/zumud-latex:latest docker/latex
	docker rm -f zumud-latex >/dev/null 2>&1 || true
	docker run -d --name zumud-latex --restart unless-stopped -p 2700:2700 ghcr.io/zumud/zumud-latex:latest
	@echo "LaTeX compiler on http://127.0.0.1:2700"

# Note: published on 0.0.0.0:2700 (not 127.0.0.1) because snap-Docker's loopback port
# proxy doesn't forward to containers under WSL; 0.0.0.0 is reachable via 127.0.0.1 from
# the host. Prod publishes 127.0.0.1:2700 (real Docker forwards loopback fine).

latex-down: ## Stop + remove the local LaTeX compiler
	docker rm -f zumud-latex >/dev/null 2>&1 || true

# Alternative to latex-up: tunnel local :2700 to a remote latex-online container.
# Provide the SSH target/options via LATEX_SSH (kept out of the repo), e.g.:
#   make latex-tunnel LATEX_SSH="-i ~/.ssh/id_ed25519 root@<host>"
latex-tunnel: ## SSH-tunnel local :2700 to a remote latex container (set LATEX_SSH=...)
	ssh -N -L 127.0.0.1:2700:127.0.0.1:2700 $(LATEX_SSH)
