"""baseline: existing schema

Revision ID: 23ef185de22c
Revises:
Create Date: 2026-07-11 15:13:53.376945

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "23ef185de22c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anonymous_resume_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("pdf_base64", sa.Text(), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("generated_at", sa.String(length=50), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anonymous_resume_sessions_id"),
        "anonymous_resume_sessions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_anonymous_resume_sessions_session_id"),
        "anonymous_resume_sessions",
        ["session_id"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("supabase_uid", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_supabase_uid"), "users", ["supabase_uid"], unique=True
    )
    op.create_table(
        "legal_authorizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("work_authorization", sa.Text(), nullable=False),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_legal_authorizations_id"), "legal_authorizations", ["id"], unique=False
    )
    op.create_table(
        "resumes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("resume_content", sa.Text(), nullable=True),
        sa.Column("resume_file_path", sa.String(), nullable=True),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_resumes_id"), "resumes", ["id"], unique=False)
    op.create_table(
        "tailoring_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "ai_model",
            sa.Enum(
                "gpt_4_1_nano",
                "gpt_4_1_mini",
                "gpt_4o",
                "gpt_4o_mini",
                "gpt_4_turbo",
                "gpt_4",
                "gpt_o1",
                "gpt_o1_preview",
                "gpt_o1_mini",
                "gpt_3_5_turbo",
                name="aimodel",
            ),
            nullable=False,
        ),
        sa.Column(
            "resume_template",
            sa.Enum(
                "Blue_Modern_Resume",
                "One_page_Simple_Resume",
                "MTeck_resume",
                name="resumetemplate",
            ),
            nullable=False,
        ),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_tailoring_options_id"), "tailoring_options", ["id"], unique=False
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("preferences_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_preferences_id"), "user_preferences", ["id"], unique=False
    )
    op.create_table(
        "user_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("latex_content", sa.Text(), nullable=False),
        sa.Column("compiler", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_templates_id"), "user_templates", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_templates_id"), table_name="user_templates")
    op.drop_table("user_templates")
    op.drop_index(op.f("ix_user_preferences_id"), table_name="user_preferences")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_tailoring_options_id"), table_name="tailoring_options")
    op.drop_table("tailoring_options")
    op.drop_index(op.f("ix_resumes_id"), table_name="resumes")
    op.drop_table("resumes")
    op.drop_index(op.f("ix_legal_authorizations_id"), table_name="legal_authorizations")
    op.drop_table("legal_authorizations")
    op.drop_index(op.f("ix_users_supabase_uid"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_anonymous_resume_sessions_session_id"),
        table_name="anonymous_resume_sessions",
    )
    op.drop_index(
        op.f("ix_anonymous_resume_sessions_id"), table_name="anonymous_resume_sessions"
    )
    op.drop_table("anonymous_resume_sessions")
    # ### end Alembic commands ###
